### ISSUE TITLE
What theme are is being used un that image?

### ISSUE THREAD

**Issue by lbonillaii** [sergdort/XcodeEquatableGenerator#2]

**Comment by sergdort** [comment]
Hi, @lbonillaii 

This is theme what I use :)
[Archive.zip](https://github.com/sergdort/XcodeEquatableGenerator/files/559873/Archive.zip)

Simply copy this files into `~/Library/Developer/Xcode/UserData/FontAndColorThemes/`

**Comment by sergdort** [comment]
I think we can close this :)
